language: node_js

node_js:
  - node

addons:
  apt:
    packages:
      - libgconf-2-4

script:
  # start server in the background
  - npm run lint
  - npm run start:ci
  # run all Cypress tests and record on the dashboard
  # - npm run cy:run
  # after all tests finish running we need
  # to kill all background jobs (like "npm start &")
  # this avoids flake in Travis jobs
  - kill $(jobs -p) || true
